# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2932b1bafa56290d922a4cb842115ff0b149db5cd59eadd56e5b39d3aca870e16301fa2321b5ae866dc85fb754ce7d9773cb1f9159c8e9144c5df0eab24a4679

test:
  secret_key_base: e2cce9873ceea14f8b7205b895f4e3873eaf5be817040cefaecc9e5fdb8c4dfe04862ec36342d9a37d4fc77266c1c26a4a38f20c856a9733cc933516f3f7b9d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
